# Generated by Django 4.0.5 on 2022-06-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoapp',
            name='input_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
